config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'login'  =>  'sessions#new'
  post  'login'  =>  'sessions#create'
  delete 'logout'  =>  'sessions#destroy'
  get 'signup'  =>  'users#new'
  resources :users
  resources :categories,only: [:index]
  resources :lessons, only: [:show, :create, :update, :index]
  resources :words,only: [:index]
  resources :results
  resources :follows, only: [:update, :destroy]
  resources :activities

  namespace :admin do
    resources :users, except: [:new, :create]
    resources :categories,only: [:new, :create, :edit, :update, :destroy, :index]
    resources :words,only: [:new, :create, :edit, :update, :destroy, :index]
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_one :result, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true
  validates_presence_of :content, :category_id

  sub_query_learned_by = "select DISTINCT word_id from results as rs, lessons as ls where ls.id=rs.lesson_id
                          and ls.user_id = ? and rs.answer_id <> ''"

  scope :learned, -> (user_id,category_id) do
    where sub_query_learned_by
    if category_id.blank?
      Word.where "id IN (#{sub_query_learned_by})",user_id
    else
      Word.where "id IN (#{sub_query_learned_by}) AND category_id = ?", user_id,category_id
    end
  end

  scope :not_learn, -> (user_id,category_id) do
    where sub_query_learned_by
    if category_id.blank?
      Word.where "id NOT IN (#{sub_query_learned_by})",user_id
    else
      Word.where "id NOT IN (#{sub_query_learned_by}) AND category_id = ?",user_id,category_id
    end
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :load_word, only: [:edit, :update, :destroy]
  before_action :admin_user, only: [:edit, :update, :new, :create, :destroy]

  def index
    @words = Word.all.paginate page: params[:page], per_page: 20
  end

  def new
    @word = Word.new
    4.times{@word.answers.build}
  end

  def create
    @word = Word.new word_params
    if @word.save
      redirect_to admin_words_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @word.update_attributes word_params
      redirect_to admin_words_path
    else
      render :edit
    end
  end

  def destroy
    @word.destroy
    redirect_to admin_words_url
  end

  private
  def word_params
    params.require(:word).permit :id, :category_id, :content, answers_attributes: [ :id, :content, :correct, :word_id]
  end

  def load_word
    @word = Word.find params[:id]
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    if params[:learn] == "all" || params[:learn].blank?
      if params[:category_id].blank?
        @words = Word.all.paginate page: params[:page], per_page: 20
      else
        category = Category.find params[:category_id]
        @words = category.words.paginate page: params[:page], per_page: 20
      end
    else
      @words = Word.send(params[:learn], current_user.id, params[:category_id]).paginate page: params[:page], per_page: 20
    end
  end
end

app/views/admin/words/edit.html.erb
<% provide(:title,t('word.title_edit'))%>
<div class="row">
  <h1><%= t('word.edit')%></h1>
  <br>
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @word] do |f|%>
      <div class="form-group">
        <%= f.label :category%>
        <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: t('word.select_list')}, {class: "form-control"} %>
      </div>
      <div class="form-group">
        <%= f.label :content%>
        <%= f.text_field :content,class: 'form-control'%>
      </div>
      <%= f.label :content , t('word.answer')%>
      <%= f.fields_for :answers do |word_answer_form| %>
        <div class="input-group">
          <span class="input-group-addon">
            <%= word_answer_form.radio_button :correct, true %>
            <%= word_answer_form.label :correct %>
          </span>
          <%= word_answer_form.text_field :content ,class: 'form-control'%>
        </div>
      <% end %>
      <br>
      <%= f.submit class: "btn btn-primary submit_button"%>
    <% end %>
  </div>
</div>

app/views/admin/words/index.html.erb
<div class="row">
  <h1 class="text-capitalize"><%= t('word.list')%></h1>
  <br>
  <%= will_paginate %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Category</th>
        <th>Content</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <% @words.each do |word|%>
      <tr>
        <td><%= word.category.name%></td>
        <td><%= word.content%></td>
        <td><%= link_to t('form.edit'),edit_admin_word_path(word)%></td>
        <td><%= link_to t('form.delete'),admin_word_path(word),method: :delete,data: {confirm: t('delete.confirmation')}%></td>
      </tr>
    <% end %>
  </table>
  <br>
  <%= link_to t('form.create'),new_admin_word_path,class: "btn btn-primary"%>	
</div>

app/views/admin/words/new.html.erb
<% provide(:title,t('word.title_new'))%>
<div class="row">
  <h1><%= t('word.new')%></h1>
  <br>
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @word] do |f|%>
      <div class="form-group">
        <%= f.label :category%>
        <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: t('word.select_list')}, {class: "form-control"} %>
      </div>
      <div class="form-group">
        <%= f.label :content%>
        <%= f.text_field :content,class: 'form-control'%>
      </div>
      <%= f.label :content , t('word.answer')%>
      <%= f.fields_for :answers do |word_answer_form| %>
        <div class="input-group">
          <span class="input-group-addon">
            <%= word_answer_form.radio_button :correct, true %>
            <%= word_answer_form.label :correct %>
          </span>
          <%= word_answer_form.text_field :content ,class: 'form-control'%>
        </div>
      <% end %>
      <br>
      <%= f.submit class: "btn btn-primary submit_button"%>
    <% end %>
  </div>
</div>